truncate table kom_manager.T_BRAND;
INSERT INTO kom_manager.T_BRAND (BRAND_CODE, BRAND_NAME, COMPANY_ID, IS_SELF, IS_INACTIVE,CREATED_TIME,UPDATED_TIME )
  SELECT BRAND_CODE, BRAND_NAME, COMPANY_ID, IS_SELF, IS_INACTIVE,CREATED_TIME,UPDATED_TIME FROM kom.T_BB_BRAND;
UPDATE kom_manager.T_BRAND SET COMPANY_ID = 2 WHERE BRAND_CODE='TECNO';
UPDATE kom_manager.T_BRAND SET COMPANY_ID = 3 WHERE BRAND_CODE='INFINIX';
UPDATE kom_manager.T_BRAND SET COMPANY_ID = 4 WHERE BRAND_CODE='ITEL';
UPDATE kom_manager.T_BRAND SET CREATED_BY = 'system';
UPDATE kom_manager.T_BRAND SET UPDATED_BY = 'system';
UPDATE kom_manager.T_BRAND SET CREATED_TIME =  NOW() WHERE CREATED_TIME IS NULL;
UPDATE kom_manager.T_BRAND SET UPDATED_TIME = NOW() WHERE UPDATED_TIME IS NULL;
UPDATE kom_manager.T_BRAND SET IS_INACTIVE = 2 WHERE IS_INACTIVE = 1;
UPDATE kom_manager.T_BRAND SET IS_INACTIVE = 1 WHERE IS_INACTIVE = 0;