#kom_manager.T_COMPANY
truncate table kom_manager.T_COMPANY;
 
INSERT INTO kom_manager.T_COMPANY (COMPANY_CODE, COMPANY_NAME, PARENT_ID, IS_INACTIVE, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
  VALUES ('TRANSSION', '传音科技', '0', '1', 'system', NOW(), 'system', NOW());

   INSERT INTO kom_manager.T_COMPANY (COMPANY_CODE, COMPANY_NAME, PARENT_ID, IS_INACTIVE, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
  VALUES ('TECNO', 'TECNO', '1', '1', 'system', NOW(), 'system', NOW());
  
   INSERT INTO kom_manager.T_COMPANY (COMPANY_CODE, COMPANY_NAME, PARENT_ID, IS_INACTIVE, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
  VALUES ('INFINIX', 'INFINIX', '1', '1', 'system', NOW(), 'system', NOW());
  
   INSERT INTO kom_manager.T_COMPANY (COMPANY_CODE, COMPANY_NAME, PARENT_ID, IS_INACTIVE, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
  VALUES ('ITEL', 'ITEL', '1', '1', 'system', NOW(), 'system', NOW());
  
   INSERT INTO kom_manager.T_COMPANY (COMPANY_CODE, COMPANY_NAME, PARENT_ID, IS_INACTIVE, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
  VALUES ('CARLCARE', '客户服务中心', '1', '1', 'system', NOW(), 'system', NOW());
  
   INSERT INTO kom_manager.T_COMPANY (COMPANY_CODE, COMPANY_NAME, PARENT_ID, IS_INACTIVE, CREATED_BY, CREATED_TIME, UPDATED_BY, UPDATED_TIME)
  VALUES ('ORAIMO', '配件事业部', '1', '1', 'system', NOW(), 'system', NOW());
