truncate table kom_manager.T_CURRENCY;
INSERT INTO kom_manager.T_CURRENCY (COMPANY_ID, FINDEX, REGION_ID, WERKS, CURRENCY_NAME,EXCHANGERATE, EXCHANGERATE2,BEGINDATE,ENDDATE, IS_INACTIVE,UPDATED_TIME )
  SELECT COMPANY_ID, FINDEX, REGION_ID, WERKS, CURRENCY_NAME,EXCHANGERATE, EXCHANGERATE2,BEGINDATE,ENDDATE, IS_INACTIVE,UPDATED_TIME FROM kom.T_BB_CURRENCY;
UPDATE kom_manager.T_CURRENCY SET CREATED_BY = 'system';
UPDATE kom_manager.T_CURRENCY SET UPDATED_BY = 'system';
UPDATE kom_manager.T_CURRENCY SET CREATED_TIME =  NOW() WHERE CREATED_TIME IS NULL;
UPDATE kom_manager.T_CURRENCY SET UPDATED_TIME = NOW() WHERE UPDATED_TIME IS NULL;
UPDATE kom_manager.T_CURRENCY SET IS_INACTIVE = 2 WHERE IS_INACTIVE = 1;
UPDATE kom_manager.T_CURRENCY SET IS_INACTIVE = 1 WHERE IS_INACTIVE = 0;
#update REGION_ID
UPDATE kom_manager.T_CURRENCY tc, kom_manager.T_REGION tr SET tc.REGION_ID = tr.ID WHERE tc.REGION_ID = tr.REGION_CODE;