truncate table kom_manager.T_DUTY;
INSERT INTO kom_manager.T_DUTY ( DUTY_CODE, DUTY_NAME, COMPANY_ID, IS_INACTIVE, CREATED_TIME, UPDATED_TIME )
  SELECT   DUTY_ID , DUTY_NAME, COMPANY_ID, IS_INACTIVE, CREATED_TIME, UPDATED_TIME  FROM kom.DT_PV_DUTIES;
UPDATE kom_manager.T_DUTY SET COMPANY_ID = 5 WHERE COMPANY_ID = 2000;
UPDATE kom_manager.T_DUTY SET COMPANY_ID = 6 WHERE COMPANY_ID = 3000;
UPDATE kom_manager.T_DUTY SET COMPANY_ID = 2 WHERE COMPANY_ID = 1000 OR COMPANY_ID = 0 OR COMPANY_ID IS NULL;
UPDATE kom_manager.T_DUTY SET CREATED_BY = 'system';
UPDATE kom_manager.T_DUTY SET UPDATED_BY = 'system';
UPDATE kom_manager.T_DUTY SET CREATED_TIME =  NOW() WHERE CREATED_TIME IS NULL;
UPDATE kom_manager.T_DUTY SET UPDATED_TIME = NOW() WHERE UPDATED_TIME IS NULL;
UPDATE kom_manager.T_DUTY SET IS_INACTIVE = 2 WHERE IS_INACTIVE = 1;
UPDATE kom_manager.T_DUTY SET IS_INACTIVE = 1 WHERE IS_INACTIVE = 0;
