truncate table kom_manager.T_EMPLOYEE;

INSERT INTO kom_manager.T_EMPLOYEE 
( EMP_ID, EMP_CODE, EMP_NAME, ID_NO,COMPANY_ID,ORG_ID,DUTY_ID,UPPER_ID,GENDER,BIRTHDAY,NATION, PHONE_NO, MOBILE_NO, NATIVE_PLACE, ZIP_CODE, IN_SERVICE,REMARK,CREATED_TIME, UPDATED_TIME )
  SELECT  EMP_ID, EMP_CODE, EMP_NAME, ID_CARD_NO,COMPANY_ID,ORG_ID,DUTY_ID,UPPER_EMP_ID,GENDER,BIRTHDAY,NATION, PHONE_NO, MOBILE_NO, NATIVE_PLACE, ZIP_CODE, IS_ON_DUTY,REMARK,CREATED_TIME, UPDATED_TIME FROM kom.DT_PV_EMPLOYEES;

INSERT INTO  T_EMPLOYEE
(`EMP_CODE`, `EMP_NAME`, `U_ID`, `ID_NO`, `COMPANY_ID`, `ORG_ID`, `DUTY_ID`, `UPPER_ID`, `REGION_ID`, 
`UPPER_NAME`, `GENDER`, `BIRTHDAY`, `NATION`, `MARRIED`, `PHONE_NO`, `MOBILE_NO`, `EMAIL`, `NATIVE_PLACE`, `ZIP_CODE`, 
`IS_HISTORY`, `IN_SERVICE`, `REMARK`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `VERSION`) VALUES 
('testItel', 'ITEL_Manager', '3319', NULL, '4', '51', '5', NULL, '3', NULL, '1', NULL, NULL, '1', NULL,
 NULL, NULL, NULL, NULL, '2', '2', NULL, 'admin', '2017-03-17 16:00:37', NULL, NULL, '0');

INSERT INTO  T_EMPLOYEE
(`EMP_CODE`, `EMP_NAME`, `U_ID`, `ID_NO`, `COMPANY_ID`, `ORG_ID`, `DUTY_ID`, `UPPER_ID`, `REGION_ID`, 
`UPPER_NAME`, `GENDER`, `BIRTHDAY`, `NATION`, `MARRIED`, `PHONE_NO`, `MOBILE_NO`, `EMAIL`, `NATIVE_PLACE`, `ZIP_CODE`,
 `IS_HISTORY`, `IN_SERVICE`, `REMARK`, `CREATED_BY`, `CREATED_TIME`, `UPDATED_BY`, `UPDATED_TIME`, `VERSION`) VALUES 
('testInfi', 'INFNIX_Manager', '3320', NULL, '3', '41', '5', NULL, '3', NULL, '1', NULL, NULL, '1', NULL,
 NULL, NULL, NULL, NULL, '2', '2', NULL, 'admin', '2017-03-17 16:00:37', NULL, NULL, '0');
  
#COMPANY_ID
UPDATE kom_manager.T_EMPLOYEE SET COMPANY_ID = 5 WHERE COMPANY_ID = 2000;
UPDATE kom_manager.T_EMPLOYEE SET COMPANY_ID = 6 WHERE COMPANY_ID = 3000;
UPDATE kom_manager.T_EMPLOYEE SET COMPANY_ID = 2 WHERE COMPANY_ID = 1000 OR COMPANY_ID = 0 OR COMPANY_ID IS NULL;
UPDATE kom_manager.T_EMPLOYEE SET CREATED_BY = 'system';
UPDATE kom_manager.T_EMPLOYEE SET UPDATED_BY = 'system';
UPDATE kom_manager.T_EMPLOYEE SET CREATED_TIME =  NOW() WHERE CREATED_TIME IS NULL;
UPDATE kom_manager.T_EMPLOYEE SET UPDATED_TIME = NOW() WHERE UPDATED_TIME IS NULL;
#DUTY_ID
UPDATE kom_manager.T_EMPLOYEE e,kom_manager.T_DUTY d SET e.DUTY_ID = d.ID WHERE e.DUTY_ID = d.DUTY_CODE;
#ORG_ID
UPDATE kom_manager.T_EMPLOYEE e,kom_manager.T_ORGANIZATION o SET e.ORG_ID = o.ID WHERE e.ORG_ID = o.ORG_ID;
#UPPER_ID
UPDATE kom_manager.T_EMPLOYEE e1 , kom_manager.T_EMPLOYEE e2 SET e1.UPPER_ID = e2.ID WHERE e1.UPPER_ID = e2.EMP_ID;
#U_ID
UPDATE kom_manager.T_EMPLOYEE e,kom_manager.T_USER u SET e.U_ID = u.ID WHERE e.EMP_CODE = u.USER_CODE;
UPDATE T_EMPLOYEE SET U_ID=(SELECT ID FROM T_USER WHERE USER_CODE='Imanager') WHERE EMP_NAME='ITEL_Manager';
UPDATE T_EMPLOYEE SET U_ID=(SELECT ID FROM T_USER WHERE USER_CODE='Infmanager') WHERE EMP_NAME='INFNIX_Manager';

#GENDER
#10110005	1011	1	男	性别
#10110010	1011	2	女	性别
#10110015	1011	3	未知	性别
UPDATE kom_manager.T_EMPLOYEE SET GENDER = 1 WHERE GENDER=10110005;
UPDATE kom_manager.T_EMPLOYEE SET GENDER = 2 WHERE GENDER=10110010;
#U_ID
#10120005	1012	1	未婚	婚姻状态
#10120010	1012	2	已婚	婚姻状态
#10120015	1012	3	离异	婚姻状态
#10120020	1012	4	丧偶	婚姻状态
#10120025	1012	5	未知	婚姻状态
UPDATE kom_manager.T_EMPLOYEE SET MARRIED = 1 WHERE MARRIED=10120005;
UPDATE kom_manager.T_EMPLOYEE SET MARRIED = 2 WHERE MARRIED=10120010;