truncate table kom_manager.T_EMPLOYEE;
INSERT INTO kom_manager.T_EMPLOYEE 
( EMP_ID, EMP_CODE, EMP_NAME, ID_NO,COMPANY_ID,ORG_ID,DUTY_ID,UPPER_ID,GENDER,BIRTHDAY,NATION, PHONE_NO, MOBILE_NO, NATIVE_PLACE, ZIP_CODE, IN_SERVICE,REMARK,CREATED_TIME, UPDATED_TIME )
  SELECT  EMP_ID, EMP_CODE, EMP_NAME, ID_CARD_NO,COMPANY_ID,ORG_ID,DUTY_ID,UPPER_EMP_ID,GENDER,BIRTHDAY,NATION, PHONE_NO, MOBILE_NO, NATIVE_PLACE, ZIP_CODE, IS_ON_DUTY,REMARK,CREATED_TIME, UPDATED_TIME FROM kom.DT_PV_EMPLOYEES;

#COMPANY_ID
UPDATE kom_manager.T_EMPLOYEE SET COMPANY_ID = 5 WHERE COMPANY_ID = 2000;
UPDATE kom_manager.T_EMPLOYEE SET COMPANY_ID = 6 WHERE COMPANY_ID = 3000;
UPDATE kom_manager.T_EMPLOYEE SET COMPANY_ID = 2 WHERE COMPANY_ID = 1000 OR COMPANY_ID = 0 OR COMPANY_ID IS NULL;
UPDATE kom_manager.T_EMPLOYEE SET CREATED_BY = 'system';
UPDATE kom_manager.T_EMPLOYEE SET UPDATED_BY = 'system';
UPDATE kom_manager.T_EMPLOYEE SET CREATED_TIME =  NOW() WHERE CREATED_TIME IS NULL;
UPDATE kom_manager.T_EMPLOYEE SET UPDATED_TIME = NOW() WHERE UPDATED_TIME IS NULL;
#DUTY_ID
UPDATE kom_manager.T_EMPLOYEE e,kom_manager.T_DUTY d SET e.DUTY_ID = d.ID WHERE e.DUTY_ID = d.DUTY_CODE;
#ORG_ID
UPDATE kom_manager.T_EMPLOYEE e,kom_manager.T_ORGANIZATION o SET e.ORG_ID = o.ID WHERE e.ORG_ID = o.ORG_ID;
#UPPER_ID
UPDATE kom_manager.T_EMPLOYEE e1 , kom_manager.T_EMPLOYEE e2 SET e1.UPPER_ID = e2.ID WHERE e1.UPPER_ID = e2.EMP_ID;
#U_ID
UPDATE kom_manager.T_EMPLOYEE e,kom_manager.T_USER u SET e.U_ID = u.ID WHERE e.EMP_CODE = u.USER_CODE;
#GENDER
#10110005	1011	1	ÄÐ	ÐÔ±ð
#10110010	1011	2	Å®	ÐÔ±ð
#10110015	1011	3	Î´Öª	ÐÔ±ð
UPDATE kom_manager.T_EMPLOYEE SET GENDER = 1 WHERE GENDER=10110005;
UPDATE kom_manager.T_EMPLOYEE SET GENDER = 2 WHERE GENDER=10110010;
#U_ID
#10120005	1012	1	Î´»é	»éÒö×´Ì¬
#10120010	1012	2	ÒÑ»é	»éÒö×´Ì¬
#10120015	1012	3	ÀëÒì	»éÒö×´Ì¬
#10120020	1012	4	É¥Å¼	»éÒö×´Ì¬
#10120025	1012	5	Î´Öª	»éÒö×´Ì¬
UPDATE kom_manager.T_EMPLOYEE SET MARRIED = 1 WHERE MARRIED=10120005;
UPDATE kom_manager.T_EMPLOYEE SET MARRIED = 2 WHERE MARRIED=10120010;