SELECT ID,USER_CODE FROM `kom_manager`.`T_USER` WHERE USER_CODE='admin' OR USER_CODE='system';

truncate kom_manager.T_ROLE_RESOURCE;
truncate kom_manager.T_ROLE_MENU;
INSERT INTO `kom_manager`.`T_ROLE_RESOURCE` (`ROLE_ID`, `RES_ID`) SELECT 2, RES_ID FROM T_SYSTEM_RESOURCE;
INSERT INTO `kom_manager`.`T_ROLE_MENU` (`ROLE_ID`, `MENU_ID`) SELECT 2, MENU_ID FROM T_SYSTEM_MENU;

#system user->admin role
INSERT INTO `kom_manager`.`T_USER_ROLE` ( `USER_ID`, `ROLE_ID`, `ROLE_NAME`, `IS_INACTIVE`, `REQ_DATE`, `CHECK_DATE`, `CHECK_STAFF`, `START_DATE`, `END_DATE`, `REMARK`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`) VALUES ('1', '2', 'admin', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#admin user->admin role
INSERT INTO `kom_manager`.`T_USER_ROLE` ( `USER_ID`, `ROLE_ID`, `ROLE_NAME`, `IS_INACTIVE`, `REQ_DATE`, `CHECK_DATE`, `CHECK_STAFF`, `START_DATE`, `END_DATE`, `REMARK`, `CREATE_BY`, `CREATE_TIME`, `UPDATE_BY`, `UPDATE_TIME`) VALUES ('2', '2', 'admin', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#admin role ->resource
SELECT ROLE_ID,ROLE_CODE FROM `kom_manager`.`T_SYSTEM_ROLE` WHERE ROLE_CODE='admin';


