truncate table kom_manager.T_ORGANIZATION;
INSERT INTO kom_manager.T_ORGANIZATION ( COMPANY_ID, PARENT_ID, ORG_ID, ORG_NAME, BIZ_ID, IS_INACTIVE,REMARK,CREATED_TIME, UPDATED_TIME )
  SELECT  COMPANY_ID, PARENT_ORG_ID, ORG_ID, ORG_NAME, ORG_DUTY_ID, IS_INACTIVE,ORG_DESC,CREATED_TIME, UPDATED_TIME   FROM kom.DT_PV_ORGANIZATIONS;
#COMPANY_ID
UPDATE kom_manager.T_ORGANIZATION SET COMPANY_ID = 5 WHERE COMPANY_ID = 2000;
UPDATE kom_manager.T_ORGANIZATION SET COMPANY_ID = 6 WHERE COMPANY_ID = 3000;
UPDATE kom_manager.T_ORGANIZATION SET COMPANY_ID = 2 WHERE COMPANY_ID = 1000 OR COMPANY_ID = 0 OR COMPANY_ID IS NULL;
UPDATE kom_manager.T_ORGANIZATION SET COMPANY_ID = 1 WHERE PARENT_ID = 0;
UPDATE kom_manager.T_ORGANIZATION SET COMPANY_ID = 2 WHERE ORG_ID = 1220;
UPDATE kom_manager.T_ORGANIZATION SET COMPANY_ID = 3 WHERE ORG_ID = 1222;
UPDATE kom_manager.T_ORGANIZATION SET COMPANY_ID = 4 WHERE ORG_ID = 1221;
UPDATE kom_manager.T_ORGANIZATION SET CREATED_BY = 'system';
UPDATE kom_manager.T_ORGANIZATION SET UPDATED_BY = 'system';
UPDATE kom_manager.T_ORGANIZATION SET CREATED_TIME =  NOW() WHERE CREATED_TIME IS NULL;
UPDATE kom_manager.T_ORGANIZATION SET UPDATED_TIME = NOW() WHERE UPDATED_TIME IS NULL;
UPDATE kom_manager.T_ORGANIZATION SET IS_INACTIVE = 2 WHERE IS_INACTIVE = 1;
UPDATE kom_manager.T_ORGANIZATION SET IS_INACTIVE = 1 WHERE IS_INACTIVE = 0;
#no use
UPDATE kom_manager.T_ORGANIZATION e,kom_manager.T_DUTY d SET e.BIZ_ID = d.ID WHERE e.BIZ_ID = d.DUTY_CODE;
#set parent id
UPDATE kom_manager.T_ORGANIZATION r1 , kom_manager.T_ORGANIZATION r2 SET r1.PARENT_ID = r2.ID WHERE r1.PARENT_ID = r2.ORG_ID;
