truncate table kom_manager.T_REGION_TYPE;
INSERT INTO `T_REGION_TYPE` VALUES ('1', '洲', '10200005', null, null, null);
INSERT INTO `T_REGION_TYPE` VALUES ('2', '国家', '10200005', null, null, null);
INSERT INTO `T_REGION_TYPE` VALUES ('3', '省份', '10200010', null, null, null);
INSERT INTO `T_REGION_TYPE` VALUES ('4', '城市', '10200015', null, null, null);

truncate table kom_manager.T_REGION;
INSERT INTO kom_manager.T_REGION ( REGION_CODE, REGION_NAME, PARENT_ID, REGION_TYPE, IS_INACTIVE,CREATED_TIME, UPDATED_TIME )
  SELECT  REGION_ID, REGION_NAME, PARENT_REGION_ID, REGION_TYPE, IS_INACTIVE,CREATED_TIME, UPDATED_TIME  FROM kom.T_BB_REGIONS;
UPDATE kom_manager.T_REGION SET CREATED_BY = 'system';
UPDATE kom_manager.T_REGION SET UPDATED_BY = 'system';
UPDATE kom_manager.T_REGION SET CREATED_TIME =  NOW() WHERE CREATED_TIME IS NULL;
UPDATE kom_manager.T_REGION SET UPDATED_TIME = NOW() WHERE UPDATED_TIME IS NULL;
UPDATE kom_manager.T_REGION SET IS_INACTIVE = 2 WHERE IS_INACTIVE = 1;
UPDATE kom_manager.T_REGION SET IS_INACTIVE = 1 WHERE IS_INACTIVE = 0;
UPDATE kom_manager.T_REGION SET REGION_TYPE = 2 WHERE REGION_TYPE = '10200005';
UPDATE kom_manager.T_REGION SET REGION_TYPE = 3 WHERE REGION_TYPE = '10200010';
UPDATE kom_manager.T_REGION SET REGION_TYPE = 4 WHERE REGION_TYPE = '10200015';
#set parent id
UPDATE kom_manager.T_REGION r1 , kom_manager.T_REGION r2 SET r1.PARENT_ID = r2.ID WHERE r1.PARENT_ID = r2.REGION_CODE
UPDATE kom_manager.T_REGION SET PARENT_ID = 0 WHERE REGION_NAME='销售区域'
