truncate table kom_manager.T_SALE;
INSERT INTO kom_manager.T_SALE(ID,BILLNO,USER_ID,USER_CODE,SHOP_ID,SHOP_CODE,COMPANY_ID,TRANTYPE,WERKS,CURRENCY_RATIO,SALE_DATE,STATUS,CREATED_BY,CREATED_TIME)
 SELECT ID,BILLNO,EMP_ID,EMP_ID, DEALER_ID ,DEALER_ID,COMPANY_ID,TRANTYPE,WERKS,CURRENCY_RATIO,SALE_DATE,FSTATUS,CREATED_BY,CREATED_TIME FROM kom.T_SHOP_SALES;
UPDATE kom_manager.T_SALE SET COMPANY_ID = 5 WHERE COMPANY_ID = 2000;
UPDATE kom_manager.T_SALE SET COMPANY_ID = 6 WHERE COMPANY_ID = 3000;
UPDATE kom_manager.T_SALE SET COMPANY_ID = 2 WHERE COMPANY_ID = 1000 OR COMPANY_ID = 0 OR COMPANY_ID IS NULL;
UPDATE kom_manager.T_SALE SET CREATED_BY = 'system';
UPDATE kom_manager.T_SALE SET UPDATED_BY = 'system';
UPDATE kom_manager.T_SALE SET CREATED_TIME =  NOW() WHERE CREATED_TIME IS NULL;
UPDATE kom_manager.T_SALE SET UPDATED_TIME = NOW() WHERE UPDATED_TIME IS NULL;
# USER_ID
UPDATE kom_manager.T_SALE sale, kom_manager.T_USER user SET sale.USER_ID = user.ID WHERE user.USER_ID = sale.USER_ID;
# USER_CODE
UPDATE kom_manager.T_SALE sale, kom_manager.T_USER user SET sale.USER_CODE = user.USER_CODE WHERE user.ID = sale.USER_ID;
# SHOP_ID
UPDATE kom_manager.T_SALE sale, kom_manager.T_SHOP shop SET sale.SHOP_ID = shop.ID WHERE shop.SHOP_ID = sale.SHOP_ID;
