truncate kom_manager.T_SHOP_GRADE;

INSERT INTO `T_SHOP_GRADE` (GRADE_NAME,BRAND_CODE,SALE_QTY,COMPANY_ID,IS_INACTIVE) VALUES ('A++', 'TECNO', '21', 2, 1);
INSERT INTO `T_SHOP_GRADE` (GRADE_NAME,BRAND_CODE,SALE_QTY,COMPANY_ID,IS_INACTIVE) VALUES ('A+', 'TECNO', '20', 2, 1);
INSERT INTO `T_SHOP_GRADE` (GRADE_NAME,BRAND_CODE,SALE_QTY,COMPANY_ID,IS_INACTIVE) VALUES ('A', 'TECNO', '19', 2, 1);
INSERT INTO `T_SHOP_GRADE` (GRADE_NAME,BRAND_CODE,SALE_QTY,COMPANY_ID,IS_INACTIVE) VALUES ('B', 'TECNO', '18', 2, 1);
INSERT INTO `T_SHOP_GRADE` (GRADE_NAME,BRAND_CODE,SALE_QTY,COMPANY_ID,IS_INACTIVE) VALUES ('C', 'TECNO', '17', 2, 1);
INSERT INTO `T_SHOP_GRADE` (GRADE_NAME,BRAND_CODE,SALE_QTY,COMPANY_ID,IS_INACTIVE) VALUES ('D', 'TECNO', '16', 2, 1);
INSERT INTO `T_SHOP_GRADE` (GRADE_NAME,BRAND_CODE,SALE_QTY,COMPANY_ID,IS_INACTIVE) VALUES ('E', 'TECNO', '15', 2, 1);
INSERT INTO `T_SHOP_GRADE` (GRADE_NAME,BRAND_CODE,SALE_QTY,COMPANY_ID,IS_INACTIVE) VALUES ('F', 'TECNO', '14', 2, 1);

