truncate table kom_manager.T_SHOP_EXTENSION;
INSERT INTO kom_manager.T_SHOP_EXTENSION 
( SHOP_ID,SHOP_AREA,RELATIONSHIP,BIZ_CATEGORY,BRAND_ONE,BRAND_TWO,BRAND_THREE)
  SELECT SHOP_ID,SHOP_AREA,RELATIONSHIP,BIZ_CATEGORY,BRANDS_FIRST,BRANDS_TWO,BRANDS_THREE FROM kom_manager.T_SHOP;