truncate table kom_manager.T_STOCK;
INSERT INTO kom_manager.T_STOCK(ID,COMPANY_ID, BILLNO,TRANTYPE,SHOP_ID,STOCK_DATE,USER_ID,WERKS,CURRENCY_RATIO,STATUS,CREATED_BY,CREATED_TIME)
 SELECT ID,COMPANY_ID, BILLNO,TRANTYPE,DEALER_ID,FDATE,EMP_ID,WERKS,CURRENCY_RATIO,FSTATUS,CREATED_BY,CREATED_TIME FROM kom.T_SHOPSTOCK_MAIN;
UPDATE kom_manager.T_STOCK SET COMPANY_ID = 5 WHERE COMPANY_ID = 2000;
UPDATE kom_manager.T_STOCK SET COMPANY_ID = 6 WHERE COMPANY_ID = 3000;
UPDATE kom_manager.T_STOCK SET COMPANY_ID = 2 WHERE COMPANY_ID = 1000 OR COMPANY_ID = 0 OR COMPANY_ID IS NULL;
UPDATE kom_manager.T_STOCK SET CREATED_BY = 'system';
UPDATE kom_manager.T_STOCK SET UPDATED_BY = 'system';
UPDATE kom_manager.T_STOCK SET CREATED_TIME =  NOW() WHERE CREATED_TIME IS NULL;
UPDATE kom_manager.T_STOCK SET UPDATED_TIME = NOW() WHERE UPDATED_TIME IS NULL;
# USER_ID
UPDATE kom_manager.T_STOCK stock, T_USER user SET stock.USER_ID = user.ID WHERE user.USER_ID = stock.USER_ID;
# USER_CODE
UPDATE kom_manager.T_STOCK stock, T_USER user SET stock.USER_CODE = user.USER_CODE WHERE user.ID = stock.USER_ID;
# SHOP_ID
UPDATE kom_manager.T_STOCK stock, T_SHOP shop SET stock.SHOP_ID = shop.ID WHERE shop.SHOP_ID = stock.SHOP_ID;