truncate table kom_manager.T_OPTION;
INSERT INTO kom_manager.T_OPTION 
( OPTION_CODE,OPTION_NAME,COMPANY_ID,PARENT_ID,OPTION_TYPE,OBJECT_ID,IS_INACTIVE)
  SELECT OPTION_ID,OPTION_NAME,COMPANY_ID,PARENT_OPTION_ID,OPTION_TYPE,BIZ_OBJECT_ID,IS_INACTIVE FROM kom.DT_PV_OPTIONS;


truncate table kom_manager.T_USER_OPTION;
INSERT INTO kom_manager.T_USER_OPTION 
( USER_ID,OPTION_ID,COMPANY_ID)
  SELECT USER_ID,OPTION_ID,COMPANY_ID FROM kom.DT_PV_USER_OPTION;

#T_USER_SHOP

truncate table kom_manager.T_USER_SHOP;

DROP VIEW VIEW_USERSHOP;
CREATE VIEW VIEW_USERSHOP AS SELECT u.ID as uid, p.ID as pid FROM T_SHOP p
INNER JOIN T_OPTION o ON o.OBJECT_ID = p.SHOP_ID
INNER JOIN T_USER_OPTION uo ON uo.OPTION_ID = o.OPTION_CODE
INNER JOIN T_USER u ON u.USER_ID = uo.USER_ID
WHERE o.IS_INACTIVE=0
GROUP BY u.ID,p.ID;

INSERT INTO kom_manager.T_USER_SHOP(USER_ID,SHOP_ID)
SELECT uid,pid FROM VIEW_USERSHOP;
DROP VIEW VIEW_USERSHOP;

UPDATE kom_manager.T_USER_SHOP SET CREATE_BY = 'system';
UPDATE kom_manager.T_USER_SHOP SET CREATE_TIME =  NOW() WHERE CREATE_TIME IS NULL;
