package com.transsion.store.resource;

public enum ExceptionDef {

	USER_ERROR(100, "USER_ERROR"),
	USER_ERROR_LOGIN(101, "USER_ERROR_LOGIN"),//用户名或密码错误，登录失败
	USER_ERROR_EMPTY_USERCODE(102,"USER_ERROR_EMPTY_USERCODE"),//用户名为空
	USER_ERROR_EMPTY_PASSWORD(103,"USER_ERROR_EMPTY_PASSWORD"),//密码为空
	USER_ERROR_USER_ALREADY_EXISTS(105,"USER_ERROR_USER_ALREADY_EXISTS"),//该用户已存在
	USER_ERROR_NONEXISTENT_USER(106,"USER_ERROR_NONEXISTENT_USER"),//用户不存在
	USER_ERROR_INACTIVE_USER(107,"USER_ERROR_INACTIVE_USER"),
	
	SALE_ERROR(200, "SALE_ERROR"),
	SALE_ERROR_EMPTY_IMEICODE(201,"SALE_ERROR_EMPTY_IMEICODE"),//imeiCode为空
	SALE_ERROR_EMPTY_USERCODE(202,"SALE_ERROR_EMPTY_USERCODE"),//userCode为空
	SALE_ERROR_EMPTY_SHOP_ID(203,"SALE_ERROR_EMPTY_SHOP_ID"),//shopID为空
	SALE_ERROR_ILLEGAL_IMEICODE(204,"SALE_ERROR_ILLEGAL_IMEICODE"),//imei号非法
	SALE_ERROR_DUPLICATE_IMEICODE(205,"SALE_ERROR_DUPLICATE_IMEICODE"),//imei号重复
	
	STOCK_ERROR(300, "STOCK_ERROR"),
	
	COMMON_ERROR(400, "BASIC_ERROR"),
	COMMON_ERROR_TOKEN_INVALID(401,"USER_ERROR_TOKEN_INVALID"),//token失效
	COMMON_ERROR_EMPTY_PARAM(402,"BASIC_ERROR_EMPTY_PARAM"),//参数为空
	COMMON_ERROR_EMPTY_COMPANY_ID(403,"COMMON_ERROR_EMPTY_COMPANY_ID"),//companyId为空
	
	BRAND_ERROR(500, "BRAND_ERROR"),
	BRAND_ERROR_NONEXISTENT_BRAND(501,"BRAND_ERROR_NONEXISTENT_BRAND"),//品牌不存在
	
	MODEL_ERROR(600, "MODEL_ERROR"),

	SHOP_ERROR(700, "SHOP_ERROR"),
	
	REGION_ERROR(800, "REGION_ERROR"),
	REGION_ERROR_EMPTY_ID(801,"REGION_ERROR_EMPTY_ID"),//ID为空
	REGION_ERROR_REGION_EXISTS_CHILD_NODE(802,"REGION_ERROR_REGION_EXISTS_CHILD_NODE"),//该销售区域存在子节点
	REGION_ERROR_REGION_BUNDLED_WITH_SHOP(803,"REGION_ERROR_REGION_BUNDLED_WITH_SHOP"),//该销售区域已绑定门店
	
	EMPLOYEE_ERROR(900,"EMPLOYEE_ERROR"),
	EMPLOYEE_ERROR_USER_ALREADY_EXISTS(901,"EMPLOYEE_ERROR_USER_ALREADY_EXISTS"),//该用户已存在
	EMPLOYEE_ERROR_EMP_ALREADY_DISTRIBUTED(902,"EMPLOYEE_ERROR_EMP_ALREADY_DISTRIBUTED"),//该员工已分配账号
	EMPLOYEE_ERROR_NONEXISTENT_EMP(903,"ERROR_MESSAGE_NONEXISTENT_EMP"),//该员工不存在
	
	SYSTEM_ERROR(1000,"SYSTEM_ERROR"),
	SYSTEM_ERROR_DUPLICATE_MENUCODE(1001,"SYSTEM_ERROR_DUPLICATE_MENUCODE"),//menuCode重复
	SYSTEM_ERROR_DUPLICATE_RESCODE(1002,"SYSTEM_ERROR_DUPLICATE_RESCODE"),//resCode重复
	SYSTEM_ERROR_DUPLICATE_ROLECODE(1003,"SYSTEM_ERROR_DUPLICATE_ROLECODE");//roleCode重复
	
	private int value;
	private String desc;

	private ExceptionDef(int value, String desc) {
		this.setValue(value);
		this.setDesc(desc);
	}

	public int getValue() {
		return value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Override
	public String toString() {
		return "[" + this.value + "]" + this.desc;
	}

}
