package com.transsion.store.exception;

public enum ExceptionDef {

	ERROR_COMMON(1, "ERROR_COMMON"),
	ERROR_COMMON_PARAM_NULL(2,"ERROR_COMMON_PARAM_NULL"),//参数为空
	ERROR_COMMON_PARAM_INVALID(3,"ERROR_COMMON_PARAM_INVALID"),//参数为空
	ERROR_COMMON_CHILDREN_EXIST(4,"ERROR_COMMON_CHILDREN_EXIST"),//
	
	ERROR_SYSTEM(100,"ERROR_SYSTEM"),
	ERROR_SYSTEM_RESOURCE_ALREADY_EXIST(101, "ERROR_SYSTEM_RESOURCE_ALREADY_EXIST"), //
	ERROR_SYSTEM_MENU_ALREADY_EXIST(102, "ERROR_SYSTEM_MENU_ALREADY_EXIST"), //
	ERROR_SYSTEM_ROLE_ALREADY_EXIST(103, "ERROR_SYSTEM_ROLE_ALREADY_EXIST"), //

	ERROR_TASK(200,"ERROR_TASK"),
	ERROR_TASK_TEMPLATE_EXIST(201,"ERROR_TASK_FILE_FORMATERROR"),
	ERROR_TASK_FILE_FORMATERROR(202,"ERROR_TASK_FILE_FORMATERROR"),
	ERROR_TASK_NONEXIST(203,"ERROR_TASK_NONEXIST"),
	
	ERROR_USER(300, "ERROR_USER"),
	ERROR_USER_LOGIN_FAILED(301, "ERROR_USER_LOGIN_FAILED"),//用户名或密码错误，登录失败
	ERROR_USER_TOKEN_INVALID(302,"ERROR_USER_TOKEN_INVALID"),//token失效
	ERROR_USER_INACTIVE(303,"ERROR_USER_INACTIVE"),//user inactive
	ERROR_USER_ALREADY_EXIST(304, "ERROR_USER_ALREADY_EXIST"), //
	ERROR_USER_NONEXIST(305, "ERROR_USER_NONEXIST"), //
	
	ERROR_REGION(400, "ERROR_REGION"),	
	ERROR_REGION_CURRENCY(401, "ERROR_REGION_CURRENCY"),
	ERROR_REGION_ALREADY_EXIST(402, "ERROR_REGION_ALREADY_EXIST"), 
	ERROR_REGION_NONEXIST(403, "ERROR_REGION_NONEXIST"), //
	ERROR_REGION_SHOP_BIND(404, "ERROR_REGION_SHOP_BIND"), //
	ERROR_REGION_CHILDREN_EXIST(405, "ERROR_REGION_CHILDREN_EXIST"), //
	
	ERROR_COMPANY(500, "ERROR_COMPANY"),
	
	ERROR_ORGANIZATION(600, "ERROR_ORGANIZATION"),
	ERROR_ORGANIZATION_DUTY(601, "ERROR_ORGANIZATION_DUTY"),
	ERROR_ORGANIZATION_CHILDREN_EXIST(602, "ERROR_ORGANIZATION_CHILDREN_EXIST"), //组织机构下有子组织,不能删除此组织机构
	ERROR_ORGANIZATION_EMP_BIND(603, "ERROR_ORGANIZATION_CHILDREN_EXIST"), //此组织机构绑定员工不能删除
	ERROR_ORGANIZATION_ALREADY_EXIST(604, "ERROR_ORGANIZATION_ALREADY_EXIST"), //
	ERROR_ORGANIZATION_INACTIVE(605, "ERROR_ORGANIZATION_INACTIVE"), //
	ERROR_ORGANIZATION_DELETE_FAILED(606, "ERROR_ORGANIZATION_DELETE_FAILED"), //
	
	ERROR_EMPLOYEE(700,"ERROR_EMPLOYEE"),
	ERROR_EMPLOYEE_ALREADY_EXIST(701,"ERROR_EMPLOYEE_ALREADY_EXIST"),
	ERROR_EMPLOYEE_NONEXIST(702,"ERROR_EMPLOYEE_NONEXIST"),
	ERROR_EMPLOYEE_OUTOFSERVICE(703,"ERROR_EMPLOYEE_OUTOFSERVICE"),
	ERROR_EMPLOYEE_USER_BIND(704,"ERROR_EMPLOYEE_USER_BIND"), //already bind user

	ERROR_BRAND(800, "ERROR_BRAND"),
	ERROR_BRAND_MODEL(801, "ERROR_MODEL"),
	ERROR_BRAND_ALREADY_EXIST(802,"ERROR_BRAND_ALREADY_EXIST"),//品牌已存在
	ERROR_BRAND_NONEXIST(803,"ERROR_BRAND_NONEXIST"),//品牌不存在
	ERROR_MODEL_ALREADY_EXIST(804,"ERROR_MODEL_ALREADY_EXIST"),//机型已存在
	ERROR_MODEL_NONEXIST(805,"ERROR_MODEL_NONEXIST"),//机型不存在

	ERROR_SHOP(900, "ERROR_SHOP"),
	ERROR_SHOP_ALREADY_EXIST(901,"ERROR_SHOP_ALREADY_EXIST"),
	ERROR_SHOP_NONEXIST(902,"ERROR_SHOP_NONEXIST"),
	ERROR_SHOP_GRADE_EXIST(903,"ERROR_SHOP_ALREADY_EXIST"),
	ERROR_SHOP_GRADE_INUSE(904,"ERROR_SHOP_GRADE_INUSE"),
	ERROR_SHOP_MATERIEL_ALREADY_EXISTS(905,"ERROR_SHOP_MATERIEL_ALREADY_EXISTS"),
	
	ERROR_SALE(1000, "ERROR_SALE"),
	ERROR_SALE_IMEI_INVALID(1000, "ERROR_SALE_IMEI_INVALID"),
	ERROR_SALE_IMEI_(1000, "ERROR_SALE_IMEI_INVALID"),

	ERROR_STOCK(1100, "ERROR_STOCK"),
	
	ERROR_UNDEFINE(9999, "ERROR_UNDEFINE");
	
	private int code;
	private String name;
	
	private ExceptionDef(int code, String name)
	{
		this.code=code;
		this.name=name;
	}
	
	public int getCode() {
		return code;
	}
	public String getName() {
		return name;
	}

}
