-- desc
-- 根据时间区间查询前10的销售员销售数量
SELECT 
    USER_CODE,
    COMPANY_ID,
    CITY_ID,
    COUNTRY_ID,
    REGION_ID,
    BRAND_CODE,
    EMP_NAME,
    CITY_NAME,
    COUNTRY_NAME,
    REGION_NAME,
    SUM(SALE_QTY) SALE_QTY
FROM
    T_REPORT_SALE_DAILY
WHERE
    SALE_DATE >= STR_TO_DATE('2016-01-02', '%Y-%m-%d %H:%i:%s')
        AND SALE_DATE <= STR_TO_DATE('2017-12-02', '%Y-%m-%d %H:%i:%s')
        AND COMPANY_ID = 1
GROUP BY USER_CODE , COMPANY_ID , CITY_ID , COUNTRY_ID , REGION_ID , BRAND_CODE, EMP_NAME , CITY_NAME , COUNTRY_NAME , REGION_NAME
ORDER BY SALE_QTY DESC
LIMIT 0 , 10