-- desc
-- 根据时间区间查询销售前10的店铺销量
SELECT 
    SHOP_ID,
    SHOP_CODE,
    COMPANY_ID,
    CITY_ID,
    COUNTRY_ID,
    REGION_ID,
    GRADE_ID,
    SHOP_NAME,
    COMPANY_NAME,
    CITY_NAME,
    COUNTRY_NAME,
    REGION_NAME,
    GRADE_NAME,
    sum(SALE_QTY) SALE_QTY
FROM
    T_REPORT_SALE_DAILY
WHERE
    SALE_DATE >= STR_TO_DATE('2016-01-02', '%Y-%m-%d %H:%i:%s')
        AND SALE_DATE <= STR_TO_DATE('2017-12-02', '%Y-%m-%d %H:%i:%s')
        AND COMPANY_ID = 1
GROUP BY SHOP_ID , SHOP_CODE, COMPANY_ID , CITY_ID , COUNTRY_ID , REGION_ID , GRADE_ID , SHOP_NAME , COMPANY_NAME , CITY_NAME , COUNTRY_NAME , REGION_NAME , GRADE_NAME
order by SALE_QTY desc limit 0, 10